--password: password

INSERT INTO USERS (ID, PASSWORD, USERNAME) VALUES (1, '{bcrypt}$2a$10$KXwaEKI9Cr1NjGOawGbw6evJ6gXmQKNTxotVJCjBtcxcIraTqP.4O', 'user');
INSERT INTO USERS (ID, PASSWORD, USERNAME) VALUES (2, '{bcrypt}$2a$10$4wx9HyC7CkX7CaYYa5Ujv.he27LQdyzrC./.P8XQ8EznaDsOQLZwO', 'admin');

INSERT INTO USER_ROLES (USER_ID, ROLES) VALUES (1, 'ROLE_USER');
INSERT INTO USER_ROLES (USER_ID, ROLES) VALUES (2, 'ROLE_USER');
INSERT INTO USER_ROLES (USER_ID, ROLES) VALUES (2, 'ROLE_ADMIN');

INSERT INTO UNITS (ID, CANCELLATION_POLICY, DESCRIPTION, IMAGE, PRICE, REGION, SCORE, TITLE) VALUES (1, 'default policy', 'some description', 'photos/12345/main.png', 12365.4, 'Athens', 5, 'unit1');
INSERT INTO UNITS (ID, CANCELLATION_POLICY, DESCRIPTION, IMAGE, PRICE, REGION, SCORE, TITLE) VALUES (2, 'default policy', 'some description', 'photos/12345/main.png', 12365.4, 'Athens', 3, 'unit1');
INSERT INTO UNITS (ID, CANCELLATION_POLICY, DESCRIPTION, IMAGE, PRICE, REGION, SCORE, TITLE) VALUES (3, 'default policy', 'some description', 'photos/12345/main.png', 12365.4, 'Athens', 4, 'unit1');

INSERT INTO REVIEWS (ID, COMMENT, SCORE, UNIT_ID, USER_ID) VALUES (1, null, 5, 1, 2);
